:toc:
:toc-title: 目次
:sectnums:
:toclevels: 5

= 店舗の機器

店舗で必要となりそうな機器の検討用メモ。

== BGM

一番の注意事項としては、商用利用が許可されている音楽を選ぶこと。勝手に音楽鳴らしたら著作権侵害になります。

有線スピーカーが使えない場合、設置の自由度の高い　Bluetooth や WiFi スピーカーから選ぶことになる。

* Bluetooth スピーカー
* WiFi スピーカー

一般的に、Wifi スピーカーは高価である。いわゆる Amazon や Google、Apple の提供するスマートスピーカーは手頃な WiFi スピーカーであり Amazon Music や Spotify、Apple Music、LINE Music などを聞くのに適しているが、それらは商用利用ができない。

そのため、現時点においては、Bluetooth スピーカーが最適である。

また、流す BGM についても、商用利用可能で月額費用が安いスマホアプリである link:https://bgm.world-scape.net/[Simple BGM] などがお勧めである。

お勧めの構成: + 
スマホ（タブレット） + BGM アプリ + Bluetooth スピーカー

=== 注意点

Bluetooth スピーカーは、Class 1 であればある程度 長距離を飛ばせるが、それには送受信側双方の機器が Class 1 である必要がある。Class 1 に対応した機器はそれほど多くはない。また、WiFi の 2.4 GHz 帯とも競合するため、Class 1 機器を使うよりは、Class 2 機器を使って、近距離の位置にスマホやタブレットを配置するのが好ましい。

送信側のスマホ（タブレット）は常時電源に接続することになると思うが、高性能なものを用意する必要はないため、専用に用意するなら中古もしくは低価格のデバイスで充分である。

== 出入の検知

=== 来客用

来客を自動で通知する。

* link:https://www.amazon.co.jp/dp/B08YDFFK6W/[人感センサー（中国製）]
* link:https://www.amazon.co.jp/dp/B079MGH8CY/[人感センサー（日本メーカー製）]
* link:https://www.amazon.co.jp/dp/B079LVB9JN/?coliid=I1Z317KB34V698&colid=22OLG7WDF3KA5&psc=1&ref_=lv_ov_lig_dp_it[開閉センサー（日本メーカー製）]


人感センサーは感度の範囲などが広すぎる場合、センサー部にテープなどを貼って調整するなどが必要かも。中華製の安い機器の場合、センサーが１つしか必要なくても、２つ入りのものを買っておくと予備として意味がありそう。

開閉センサーは取り付け部の距離などで制約があるかもしれないので、取付位置などをよく考えて買うこと。

=== 従業員、宅配業者用

来訪を通知する。 +
ドアが施錠されている場合、開閉センサーは使えない。

* 人感センサー
* 監視カメラ

== 監視カメラ

監視カメラ

=== 要求

* 鮮明であること
* （電源が取れない場合）電源が長持ちすること

==== 屋内

基本は常時録画、特定エリアは動体検知などあるかもしれない。

* 常時録画
* 動体検知時
** 通知機能

==== 屋外

基本は動体検知録画。

* 防水
* 夜間暗視
* 動体検知時
** 録画機能
** 通知機能

===== お勧めの屋外カメラ

いくつか候補を挙げるが、いずれも別途 SD カードを用意すべき。
（クラウド転送機能があっても、別途料金が必要なため）

link:https://www.amazon.co.jp/dp/B09GYHLRCW/[【2022年新型・300万高画素】YESKAMO 防犯カメラ 屋外 ソーラー Wi-Fi 電池式 10400mAh ONVIF対応 PIR人感]

* ぽっと出のメーカーではない（日本市場で 5 年弱の販売実績）
* ONVIF 対応しているので、一般的な監視システムにも統合可能
* ソーラー式なので電源取りづらいところでも使いやすい

ただし、

* 運用してみて、ソーラー充電によるバッテリーが充分もたないとわかった場合、別途電源を取る必要がある。

link:https://www.amazon.co.jp/dp/B097NXYYJR/[TP-Link WiFi ネットワークカメラ 屋外カメラ 防犯カメラ 3年保証 音声通話可能 3年保証 Tapo C310/A]

* それなりに名の知れたメーカー
* 安いわりに評価が高い

ただし、

* 防水とうたっている割には防水対策が不十分なようです。そのため、きちんと自分で防水処理する必要があります。具体的には電源アダプタを防水 PVA ボックスに収納して、隙間にはシーリング材で封止するなどを徹底しましょう。


==== 注意事項

* 記録用のストレージは永久には持たない。HDD や SD は稼働時間にも拠るが消耗品なので、1年～2年ぐらいで交換と考える。

* スマホアプリでのみ設定や通知を行うものがあるが、マイナーなメーカーだとアプリが提供されなくなったり、更新がされないために新しい OS で使えないなどのリスクがあることに注意します。

==== 関連機材

* link:https://www.amazon.co.jp/dp/B09DKRJYSF/[MicroSD カード 128GB]
* link:https://www.amazon.co.jp/dp/B0834NFP5C/[ポールへのカメラ取付金具]
* link:https://www.amazon.co.jp/dp/B01F8ES45A/[未来工業 防水 PVA ボックス]
* link:https://www.amazon.co.jp/dp/B01DNRR8NI/[未来工業 コネクタ PF管φ16用]
* link:https://www.amazon.co.jp/dp/B06VWQDW8S/[防雨 電源　延長コード]
* link:https://www.amazon.co.jp/dp/B003QNAPXA/[シーリング材]

== 空気清浄機

面積、用途（空気清浄、脱臭）などにも依存する。

AirDog や BlueAir などは大面積にも使えて便利そうだが、いかんせん高価で気軽に試すこともできない。

中華の安いのは清浄効果は値段ふまえればまずまずかもしれないが、脱臭効果はよくわからない。中華を買うぐらいなら、アイリスオーヤマを買ったほうが良いと思う。

脱臭なども考えると、そこまで広くない環境であれば素直に Sharp / Panasonic / DAIKIN などの日本製でよいのでないでしょうか？

DAIKIN だと link:https://www.daikin.co.jp/air/technology/our-technology/streamer[ストリーマ放電]で強力な脱臭／分解が期待できます。

* link:https://www.amazon.co.jp/dp/B08PQJYWP9/[DAIKIN 空気清浄機]

なお、加湿機能つきのモデルで加湿機能を使うために水を入れると定期的な水垢などの掃除がかなり手間になります。加湿が不要なら、加湿機能を使わないほうがメンテナンスが楽になります。

== お買い物候補リスト


link:https://www.amazon.jp/hz/wishlist/ls/22OLG7WDF3KA5[amazon お買い物リスト]




